#!/bin/bash

main_dir=`basename test_cirrus_ngs/`

for dir in $main_dir/test*; do
    if [ -d $dir ]; then
        for file in $dir/test*.py; do
            echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
            echo $file
            echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
            python $file
            echo
        done
    fi
done
