steps:
   - "fastqc"
   - "trim"
   - "cut_adapt"
   - "align_and_count"
   - "merge_counts"
   - "multiqc"
fastqc:
    script_path: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args: []
trim:
    script_path: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args:
        - 1     # number of threads
        - 15    # minlen for trimmomatic
cut_adapt:
    script_path: "SmallRNASeq/bowtie2/cutadapt"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args:
        - 1     # number of threads
        - 2    # minlengt for read
        - "TGGAATTCTCGGGTGCCAAGG" # adapter sequence
align_and_count:
    script_path: "SmallRNASeq/bowtie2/bowtie2_and_count"
    download_suffix: ".cut{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
merge_counts:  # merge the count files
    script_path: "SmallRNASeq/bowtie2/miRNA_merge_counts"
    download_suffix: ".counts.txt"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
    extra_bash_args: []
multiqc:
    script_path: "multiqc"
    download_suffix: ""
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
    extra_bash_args: []
