steps:
    - "fastqc"
    - "trim"
    - "align"
    - "multiqc"
    - "make_tag_directory"
    - "make_UCSC_file"
    - "find_peaks"
    - "annotate_peaks"
    - "pos2bed"
    - "find_motifs_genome"
fastqc:
    script_path: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args: []
trim:
    script_path: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
        - 36    # minlen for trimmomatic
align:
    script_path: "ChiPSeq/homer/bowtie"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
multiqc:
    script_path: "multiqc"
    download_suffix: ""
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
    extra_bash_args: []
make_tag_directory:
    script_path: "ChiPSeq/homer/make_tag_directory"
    download_suffix: ".sam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args: []
make_UCSC_file:
    script_path: "ChiPSeq/homer/make_UCSC_file"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args: []
find_peaks:
    script_path: "ChiPSeq/homer/findpeaks"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
    extra_bash_args: []
annotate_peaks:
    script_path: "ChiPSeq/homer/annotate_peaks"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
    extra_bash_args: []
pos2bed:
    script_path: "ChiPSeq/homer/pos2bed"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
    extra_bash_args: []
find_motifs_genome:
    script_path: "ChiPSeq/homer/find_motifs_genome"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    by_pair: True
    extra_bash_args:
        - 4     # number of threads
