steps:
   - "fastqc"
   - "trim"
   - "align"
   - "multiqc"
   - "variant_calling"

fastqc:
    script_path: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args: []
trim:
    script_path: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
        - 27    # minlen for trimmomatic
align:
    script_path: "RNASeq/star_gatk/gatk_align"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
variant_calling:
    script_path: "RNASeq/star_gatk/gatk_vc"
    download_suffix: ".Aligned.out.sorted.bam"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
multiqc:
    script_path: "multiqc"
    download_suffix: ""
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
    extra_bash_args: []
