steps:
   - "fastqc"
   - "trim"
   - "align_count"
   - "multiqc"
   - "merge_counts"
fastqc:
    script_path: "fastqc"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args: []
trim:
    script_path: "trim"
    download_suffix: ~
    input_is_output: False
    can_be_zipped: True
    uses_chromosomes: False
    extra_bash_args:
        - 4     # number of threads
        - 27    # min length to keep
align_count:
    script_path: "RNASeq/star_rsem/cal_expression"
    download_suffix: ".trim{}"
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    extra_bash_args:
        - 4     # num threads
merge_counts:
    script_path: "RNASeq/star_rsem/merge"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
    extra_bash_args: []
multiqc:
    script_path: "multiqc"
    download_suffix: ~
    input_is_output: True
    can_be_zipped: False
    uses_chromosomes: False
    all_samples: True
    extra_bash_args: []
