#qsub -pe smp 4 postalignment_base.sh T13
qsub -pe smp 4 postalignment_base.sh T17
qsub -pe smp 4 postalignment_base.sh T18
qsub -pe smp 4 postalignment_base.sh T22
qsub -pe smp 4 postalignment_base.sh T23
qsub -pe smp 4 postalignment_base.sh T2
qsub -pe smp 4 postalignment_base.sh T33
qsub -pe smp 4 postalignment_base.sh T36
qsub -pe smp 4 postalignment_base.sh T37
qsub -pe smp 4 postalignment_base.sh T43
qsub -pe smp 4 postalignment_base.sh T44
qsub -pe smp 4 postalignment_base.sh T45
qsub -pe smp 4 postalignment_base.sh T5
qsub -pe smp 4 postalignment_base.sh T7
